name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
          check-latest: true
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ github.repository }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ github.repository }}-
      - run: yarn install --frozen-lockfile
      - run: yarn build
